// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_flow_bank/test/bloc/onboarding_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:flutter_flow_bank/models/bank_account.dart' as _i3;
import 'package:flutter_flow_bank/services/api_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBankAccount_1 extends _i1.SmartFake implements _i3.BankAccount {
  _FakeBankAccount_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: '',
      ) as String);
  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
  @override
  _i5.Future<String> getHelloWorld() => (super.noSuchMethod(
        Invocation.method(
          #getHelloWorld,
          [],
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<String> createAccount(String? encryptedValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [encryptedValue],
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<String> encryptValue(Map<String, dynamic>? plainValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptValue,
          [plainValue],
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<_i3.BankAccount> decryptValue(String? encryptedValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptValue,
          [encryptedValue],
        ),
        returnValue: _i5.Future<_i3.BankAccount>.value(_FakeBankAccount_1(
          this,
          Invocation.method(
            #decryptValue,
            [encryptedValue],
          ),
        )),
      ) as _i5.Future<_i3.BankAccount>);
}
